name: Perl

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Perl
      uses: perl/setup-perl@v1
      with:
        perl-version: '5.32'
    - name: Run script
      run: perl script.pl
